import React from "react";
import Head from "next/head";
import Header from "../dashboardComponents/Header";
import TopCards from "../dashboardComponents/TopCards";
import RecentOrders from "../dashboardComponents/RecentOrders";
import BarChart from "../dashboardComponents/BarChart";
import SideBar from "@/dashboardComponents/SideBar.jsx";

const Home = () => {
  return (
    <SideBar>
      <Head>
        <title>Simple Dashboard</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen">
        <Header />
        <TopCards />
        <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </SideBar>
  );
};

export default Home;
